<?php


//Add folder to wp-content directory by the name of the customer and order ID ;


add_action('woocommerce_before_thankyou', 'wpb_update_order_table');

function wpb_update_order_table($order_id){
    
    //Check if 'GET' request on page
    if(!$_SERVER['REQUEST_METHOD'] == 'GET'){
        return; 
    }

    
    // Update woocommerce_order_items table Customer Directory
    
    global $wpdb ;
    $wpb_order = wc_get_order($order_id);
    $wpb_order_id = $wpb_order -> get_id() ;
    $old_string = array(" ", ".", "&", "%", "#", "$", "@", "^", "*");
    $customer_name = strtolower(str_replace($old_string, "_" , $wpb_order->get_formatted_billing_full_name()));
    $wpb_customer_dir = $customer_name.'-'.$wpb_order_id;

    $upload = wp_upload_dir() ;
    $upload_dir = $upload['basedir'];
    $upload_dir = $upload_dir . '/wpb/order_dir/'. $customer_name . '-' . $wpb_order_id;

    if(!file_exists($upload_dir)):
        wp_mkdir_p($upload_dir);
    endif;

    

        $wpdb -> query("UPDATE {$wpdb -> prefix}woocommerce_order_items 
        SET customer_dir = '$wpb_customer_dir' 
        WHERE order_id = $wpb_order_id");
        
}

//Changing upload directory 
/*
 Here, we need to add a filter called 'upload_dir', for this filter an array needed to be passed. In the call back funciton we define the array. 
*/

function wpb_upload_dir($path){

    global $wpdb;

    $wpb_order_id = $_POST['wpb_order_id'] ;

    $wpb_query = $wpdb -> get_results( "SELECT * FROM {$wpdb -> prefix}woocommerce_order_items WHERE order_id = $wpb_order_id", OBJECT);

    // echo '<pre>';
    // print_r($wpb_query);
    // echo '</pre>';

    $wpb_dir = '/wpb/order_dir/'. $wpb_query[0] -> customer_dir;
    
    $path['path'] = $path['basedir'] . $wpb_dir;

    $path['url'] = $path['basedir'].$wpb_dir;

    return $path ;
}



// Adding upload button to order page ;

add_action('wpb_upload_docs_handle', 'wpb_upload_docs_handle_callback') ;

function wpb_upload_docs_handle_callback(){

    global $order;
    $wpb_order_id = $order -> get_id() ;
    global $wpdb ;

?>
<form class="wpb_upload_form" method="post" action="" enctype="multipart/form-data">
    <input type="file" name="wpb_upload_input" class="wpb_upload_input" multiple="false" />
    <input type="hidden" name="wpb_order_id" class="wpb_order_id" value="<?php echo $order -> get_id() ;?>" />
    <button type="button" class="wpb_upload_btn">Dépôt documents</button>
    <span class="wpb_uploaded_filename"></span>
</form>

<?php
$path = wp_upload_dir();
if($_SERVER['REQUEST_METHOD'] == 'POST'){
    if(!isset($file)){
        $file = $_FILES['wpb_upload_input']['name'];
    }

    $target_file = wp_upload_dir()['basedir']. 'wpb/order_dir';

    $upload_query = "INSERT INTO `{$wpdb -> prefix}wpb_upload_items` (`order_id`, `upload_date`, `uploaded_file`) VALUES ('{$wpb_order_id}', CURRENT_DATE(), '{$file}')";


    
    if ( ! function_exists( 'wp_handle_upload' ) ) {
        require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }
    $uploadedfile = $_FILES['wpb_upload_input'];
    
    $upload_overrides = array(
        'test_form' => false
    );

    add_filter('upload_dir', 'wpb_upload_dir');
    $movefile = wp_handle_upload($uploadedfile, $upload_overrides);
    remove_filter('upload_dir', 'wpb_upload_dir');

    
    
    if ( $movefile && ! isset( $movefile['error'] ) ) {
        $wpdb -> query($upload_query);    

        // Construct the object array.
			$object = array(
				'post_title'     => basename( $movefile['file'] ),
				'post_content'   => '<img scr='.$movefile['url'].'</img>',
				'post_mime_type' => $movefile['type'],
				'guid'           => $target_file,
				'context'        => 'import',
				'post_status'    => 'private',
			);

			// Save the data.
			$id = wp_insert_attachment( $object, $movefile['file'] );
    } else {
        /*
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $movefile['error'];
    }
}

//Handle After Upload ;
$upload_handle_query = "SELECT * FROM {$wpdb -> prefix}wpb_upload_items WHERE order_id = $wpb_order_id";    
$up_results = $wpdb -> get_results($upload_handle_query);

?>
<table class="wpb-document-table wpb_uploaded_table">
    <?php
        if(count($up_results) > 0):
    ?>
    <thead>
        <tr>
            <td>Nom du document</td>
            <td>Date</td>
        </tr>
    </thead>
    <?php
        foreach($up_results as $result):
    ?>
    <tr>
        <td class="upload_doc_name"><?php echo $result -> uploaded_file;?></td>
        <td class="upload_doc_date"><?php echo date_format(new DateTime($result -> upload_date), 'd/m/Y');?></td>
    </tr>

    <?php endforeach ;
        endif;
    ?>
</table>


<?php


}